/**
 * Auto-generated table and column constants
 * Generated on: 2026-05-28T07:35:24.993Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate:constants' to regenerate
 */

/**
 * Table names enum for type-safe table references
 */
export enum TableNames {
    ASSIGNMENT = 'x_itaccess_assignment',
    REQUEST = 'x_itaccess_request',
    ACCESS_TYPE = 'x_itaccess_access_type',
    APPROVAL = 'x_itaccess_approval',
}

/**
 * Column names for each table
 * Use with TableColumns[TableNames.ACCESS_REQUEST].REQUESTED_BY
 */
export const TableColumns = {
    ASSIGNMENT: {
        USER: 'user',
        ACCESS_TYPE: 'access_type',
        ACCESS_REQUEST: 'access_request',
        GRANTED_DATE: 'granted_date',
        EXPIRATION_DATE: 'expiration_date',
        GRANTED_BY: 'granted_by',
        STATUS: 'status',
        REVOKED_DATE: 'revoked_date',
        REVOKED_BY: 'revoked_by',
        REVOCATION_REASON: 'revocation_reason',
        NOTES: 'notes',
        AUTO_RENEWED: 'auto_renewed',
        LAST_REVIEWED_DATE: 'last_reviewed_date',
        REVIEWED_BY: 'reviewed_by',
    },
    REQUEST: {
        NUMBER: 'number',
        REQUESTED_FOR: 'requested_for',
        REQUESTED_BY: 'requested_by',
        ACCESS_TYPE: 'access_type',
        BUSINESS_JUSTIFICATION: 'business_justification',
        STATE: 'state',
        PRIORITY: 'priority',
        REQUESTED_DATE: 'requested_date',
        REQUIRED_DATE: 'required_date',
        APPROVAL_DATE: 'approval_date',
        COMPLETION_DATE: 'completion_date',
        APPROVED_BY: 'approved_by',
        REJECTION_REASON: 'rejection_reason',
        ASSIGNED_TO: 'assigned_to',
        WORK_NOTES: 'work_notes',
        IS_EMERGENCY: 'is_emergency',
        MANAGER_APPROVAL_REQUIRED: 'manager_approval_required',
    },
    ACCESS_TYPE: {
        NAME: 'name',
        DESCRIPTION: 'description',
        CATEGORY: 'category',
        REQUIRES_APPROVAL: 'requires_approval',
        AUTO_PROVISION: 'auto_provision',
        APPROVAL_GROUP: 'approval_group',
        FULFILLMENT_GROUP: 'fulfillment_group',
        ACTIVE: 'active',
        SLA_HOURS: 'sla_hours',
        RISK_LEVEL: 'risk_level',
        DOCUMENTATION_URL: 'documentation_url',
        COST_PER_USER: 'cost_per_user',
    },
    APPROVAL: {
        ACCESS_REQUEST: 'access_request',
        APPROVER: 'approver',
        APPROVAL_TYPE: 'approval_type',
        STATE: 'state',
        REQUESTED_DATE: 'requested_date',
        APPROVAL_DATE: 'approval_date',
        COMMENTS: 'comments',
        SEQUENCE: 'sequence',
    },
} as const;

/**
 * Type helper for table column names
 */
export type TableColumnNames<T extends TableNames> = keyof typeof TableColumns[T];

/**
 * Type helper to get column name string from table
 */
export type ColumnValue<T extends TableNames, C extends TableColumnNames<T>> = typeof TableColumns[T][C];
